name: Create Release ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare plugin folder
        run: |
          # Erstelle den Hauptordner mit festem Namen
          mkdir -p release/soulcraft-form-pdf
          
          # Kopiere alle Dateien außer `.git` und `.github` in diesen Ordner
          rsync -a \
            --exclude='.git' \
            --exclude='.github' \
            . release/soulcraft-form-pdf

      - name: Create ZIP file
        run: |
          # Erstelle ZIP-Datei vom festgelegten Hauptordner
          cd release
          zip -r ../soulcraft-form-pdf.zip soulcraft-form-pdf
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: soulcraft-form-pdf.zip
