name: Create Release ZIP
on:
  workflow_dispatch:    # Ermöglicht manuelle Ausführung

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare plugin folder
        run: |
          # Erstelle den Hauptordner mit festem Namen
          mkdir -p release/soulcraft-form-pdf
          
          # Kopiere alle Dateien außer `.git` und `.github` in diesen Ordner
          rsync -a \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='.gitignore' \
            --exclude='README.md' \
            . release/soulcraft-form-pdf

      - name: Create ZIP file
        run: |
          cd release
          zip -r ../soulcraft-form-pdf.zip soulcraft-form-pdf
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./soulcraft-form-pdf.zip
          asset_name: soulcraft-form-pdf.zip
          asset_content_type: application/zip
